package com.whan.hibernate.usermanage;

// Generated 2012-5-7 10:42:54 by Hibernate Tools 3.4.0.CR1

/**
 * AdmGroupRole generated by hbm2java
 */
public class AdmGroupRole implements java.io.Serializable {

	private Integer id;
	private AdmRole admRole;
	private AdmGroup admGroup;

	public AdmGroupRole() {
	}

	public AdmGroupRole(AdmRole admRole, AdmGroup admGroup) {
		this.admRole = admRole;
		this.admGroup = admGroup;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AdmRole getAdmRole() {
		return this.admRole;
	}

	public void setAdmRole(AdmRole admRole) {
		this.admRole = admRole;
	}

	public AdmGroup getAdmGroup() {
		return this.admGroup;
	}

	public void setAdmGroup(AdmGroup admGroup) {
		this.admGroup = admGroup;
	}

}
