package com.whan.hibernate.usermanage;

// Generated 2012-5-7 10:42:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AdmGroup generated by hbm2java
 */
public class AdmGroup implements java.io.Serializable {

	private String groupId;
	private String groupName;
	private String aliasName;
	private Set admGroupRoles = new HashSet(0);
	private Set admUserGroups = new HashSet(0);

	public AdmGroup() {
	}

	public AdmGroup(String groupId) {
		this.groupId = groupId;
	}

	public AdmGroup(String groupId, String groupName, String aliasName,
			Set admGroupRoles, Set admUserGroups) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.aliasName = aliasName;
		this.admGroupRoles = admGroupRoles;
		this.admUserGroups = admUserGroups;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getAliasName() {
		return this.aliasName;
	}

	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	public Set getAdmGroupRoles() {
		return this.admGroupRoles;
	}

	public void setAdmGroupRoles(Set admGroupRoles) {
		this.admGroupRoles = admGroupRoles;
	}

	public Set getAdmUserGroups() {
		return this.admUserGroups;
	}

	public void setAdmUserGroups(Set admUserGroups) {
		this.admUserGroups = admUserGroups;
	}

}
