package com.whan.hibernate.usermanage;

// Generated 2012-5-7 10:42:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdmLogonInfo generated by hbm2java
 */
public class AdmLogonInfo implements java.io.Serializable {

	private Integer id;
	private String userId;
	private Date logonDate;
	private String logonIp;

	public AdmLogonInfo() {
	}

	public AdmLogonInfo(Date logonDate) {
		this.logonDate = logonDate;
	}

	public AdmLogonInfo(String userId, Date logonDate, String logonIp) {
		this.userId = userId;
		this.logonDate = logonDate;
		this.logonIp = logonIp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Date getLogonDate() {
		return this.logonDate;
	}

	public void setLogonDate(Date logonDate) {
		this.logonDate = logonDate;
	}

	public String getLogonIp() {
		return this.logonIp;
	}

	public void setLogonIp(String logonIp) {
		this.logonIp = logonIp;
	}

}
