package com.whan.hibernate.usermanage;

// Generated 2012-5-7 10:42:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AdmResgroup generated by hbm2java
 */
public class AdmResgroup implements java.io.Serializable {

	private String resgroupId;
	private String resgroupName;
	private Set admResgroupRoles = new HashSet(0);
	private Set admReses = new HashSet(0);

	public AdmResgroup() {
	}

	public AdmResgroup(String resgroupId) {
		this.resgroupId = resgroupId;
	}

	public AdmResgroup(String resgroupId, String resgroupName,
			Set admResgroupRoles, Set admReses) {
		this.resgroupId = resgroupId;
		this.resgroupName = resgroupName;
		this.admResgroupRoles = admResgroupRoles;
		this.admReses = admReses;
	}

	public String getResgroupId() {
		return this.resgroupId;
	}

	public void setResgroupId(String resgroupId) {
		this.resgroupId = resgroupId;
	}

	public String getResgroupName() {
		return this.resgroupName;
	}

	public void setResgroupName(String resgroupName) {
		this.resgroupName = resgroupName;
	}

	public Set getAdmResgroupRoles() {
		return this.admResgroupRoles;
	}

	public void setAdmResgroupRoles(Set admResgroupRoles) {
		this.admResgroupRoles = admResgroupRoles;
	}

	public Set getAdmReses() {
		return this.admReses;
	}

	public void setAdmReses(Set admReses) {
		this.admReses = admReses;
	}

}
