package com.whan.hibernate.usermanage;

// Generated 2012-5-7 10:42:54 by Hibernate Tools 3.4.0.CR1

/**
 * AdmResgroupRole generated by hbm2java
 */
public class AdmResgroupRole implements java.io.Serializable {

	private Integer id;
	private AdmRole admRole;
	private AdmResgroup admResgroup;

	public AdmResgroupRole() {
	}

	public AdmResgroupRole(AdmRole admRole, AdmResgroup admResgroup) {
		this.admRole = admRole;
		this.admResgroup = admResgroup;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AdmRole getAdmRole() {
		return this.admRole;
	}

	public void setAdmRole(AdmRole admRole) {
		this.admRole = admRole;
	}

	public AdmResgroup getAdmResgroup() {
		return this.admResgroup;
	}

	public void setAdmResgroup(AdmResgroup admResgroup) {
		this.admResgroup = admResgroup;
	}

}
