package com.whan.hibernate.usermanage;

// Generated 2012-5-17 18:44:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdmUser generated by hbm2java
 */
public class AdmUser implements java.io.Serializable {

	private String userId;
	private String userName;
	private String password;
	private String accountStatus;
	private Date lockDate;
	private Date expireDate;
	private Date createdDate;
	private String aliasName;
	private String remarks;

	public AdmUser() {
	}

	public AdmUser(String userId, String userName, String accountStatus) {
		this.userId = userId;
		this.userName = userName;
		this.accountStatus = accountStatus;
	}

	public AdmUser(String userId, String userName, String password,
			String accountStatus, Date lockDate, Date expireDate,
			Date createdDate, String aliasName, String remarks) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.accountStatus = accountStatus;
		this.lockDate = lockDate;
		this.expireDate = expireDate;
		this.createdDate = createdDate;
		this.aliasName = aliasName;
		this.remarks = remarks;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAccountStatus() {
		return this.accountStatus;
	}

	public void setAccountStatus(String accountStatus) {
		this.accountStatus = accountStatus;
	}

	public Date getLockDate() {
		return this.lockDate;
	}

	public void setLockDate(Date lockDate) {
		this.lockDate = lockDate;
	}

	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getAliasName() {
		return this.aliasName;
	}

	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
