package com.whan.hibernate.usermanage;

// Generated 2012-5-7 10:42:54 by Hibernate Tools 3.4.0.CR1

/**
 * AdmUserFavorites generated by hbm2java
 */
public class AdmUserFavorites implements java.io.Serializable {

	private Integer id;
	private AdmUser admUser;
	private AdmRes admRes;
	private Integer ticks;

	public AdmUserFavorites() {
	}

	public AdmUserFavorites(AdmUser admUser, AdmRes admRes) {
		this.admUser = admUser;
		this.admRes = admRes;
	}

	public AdmUserFavorites(AdmUser admUser, AdmRes admRes, Integer ticks) {
		this.admUser = admUser;
		this.admRes = admRes;
		this.ticks = ticks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AdmUser getAdmUser() {
		return this.admUser;
	}

	public void setAdmUser(AdmUser admUser) {
		this.admUser = admUser;
	}

	public AdmRes getAdmRes() {
		return this.admRes;
	}

	public void setAdmRes(AdmRes admRes) {
		this.admRes = admRes;
	}

	public Integer getTicks() {
		return this.ticks;
	}

	public void setTicks(Integer ticks) {
		this.ticks = ticks;
	}

}
